<a href="https://colab.research.google.com/github/unnati-negi/GENAI/blob/main/Healthcare_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
!pip install hmmlearn
from hmmlearn import hmm

Requirement already satisfied: hmmlearn in /usr/local/lib/python3.12/dist-packages (0.3.3)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.12/dist-packages (from hmmlearn) (2.0.2)
Requirement already satisfied: scikit-learn!=0.22.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from hmmlearn) (1.6.1)
Requirement already satisfied: scipy>=0.19 in /usr/local/lib/python3.12/dist-packages (from hmmlearn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0,>=0.16->hmmlearn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0,>=0.16->hmmlearn) (3.6.0)

In [ ]:
data = pd.read_csv("/content/Heart_Failure_Details.csv")

data.head()

,S no.,age,anaemia,creatinine phosphokinase,diabetes,ejection fraction,high bp,platelets,serum creatinine,sex,smoking,death
0,1,75.0,0,582,0,20,1,265000.00,1.9,1,0,1
1,2,55.0,0,7861,0,38,0,263358.03,1.1,1,0,1
2,3,65.0,0,146,0,20,0,162000.00,1.3,1,1,1
3,4,50.0,1,111,0,20,0,210000.00,1.9,1,0,1
4,5,65.0,1,160,1,20,0,327000.00,2.7,0,0,1

In [ ]:
data.describe()

,S no.,age,anaemia,creatinine phosphokinase,diabetes,ejection fraction,high bp,platelets,serum creatinine,sex,smoking,death
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.00000,299.00000
mean,150.000000,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,0.648829,0.32107,0.32107
std,86.458082,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,0.478136,0.46767,0.46767
min,1.000000,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,0.000000,0.00000,0.00000
25%,75.500000,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,0.000000,0.00000,0.00000
50%,150.000000,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,1.000000,0.00000,0.00000
75%,224.500000,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,1.000000,1.00000,1.00000
max,299.000000,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,1.000000,1.00000,1.00000

In [ ]:
marginal_prob = data['death'].mean()

print("P(Death Event) =", marginal_prob)

P(Death Event) = 0.3210702341137124

In [ ]:
joint_prob = len(data[(data['age'] > 60) & (data['death'] == 1)]) / len(data)

print("P(Age > 60 AND Death = 1) =", joint_prob)

P(Age > 60 AND Death = 1) = 0.17391304347826086

In [ ]:
age = data[data['age'] > 60]

conditional_prob = age['death'].mean()

print("P(Death | Age > 60) =", conditional_prob)

if conditional_prob > marginal_prob:
    print("Older patients have higher mortality risk.")
else:
    print("Older patients do not have higher mortality risk.")

P(Death | Age > 60) = 0.3795620437956204
Older patients have higher mortality risk.

In [ ]:
mle = data['death'].sum() / len(data)

print("MLE Estimate of Death Probability =", mle)

MLE Estimate of Death Probability = 0.3210702341137124

In [ ]:
p = mle
q = 0.25

kldiv = p*np.log(p/q) + (1-p)*np.log((1-p)/(1-q))

print("KL Divergence =", kldiv)

KL Divergence = 0.012740237651508016

In [ ]:
states = ["Healthy", "At Risk", "Critical"]

transition_matrix = np.array([
    [0.7, 0.2, 0.1],
    [0.3, 0.5, 0.2],
    [0.1, 0.3, 0.6]
])

current_state = 0

print("Patient Health Progression")

for day in range(10):
    current_state = np.random.choice([0,1,2], p=transition_matrix[current_state])
    print("Day", day, "State:", states[current_state])

Patient Health Progression
Day 0 State: Healthy
Day 1 State: Healthy
Day 2 State: Healthy
Day 3 State: Healthy
Day 4 State: Healthy
Day 5 State: Healthy
Day 6 State: At Risk
Day 7 State: At Risk
Day 8 State: Healthy
Day 9 State: Healthy

In [ ]:
health_sequence = data['death'].values.reshape(-1,1)

model = hmm.MultinomialHMM(n_components=2)

model.fit(health_sequence)

hidden_states = model.predict(health_sequence)

print("First 20 Hidden States:", hidden_states[:20])

WARNING:hmmlearn.hmm:MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340

First 20 Hidden States: [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]